### PR TITLE
Added functionality to generate possible user prompt words from manim code

### PR DESCRIPTION
**Pull request by Puiching-Memory**
Use Wenxin Word GPT integrated with langchain.
There is an additional Settings file to store the API KEY.

Honestly, this is the first time I've ever contributed to another project. I'm not sure why gitignore didn't work on this API_Key.cfg file

### CODE REVIEW

**Comment by Puiching-Memory** [comment]
And I realized I had misspelled the word😢

**Comment by 360macky** [comment]
Hi @Puiching-Memory!

How exciting that this is your first contribution to an external project.
I'm reviewing it right now..., I have to have a Baidu account first...

**Comment by 360macky** [comment]
@Puiching-Memory Do you know how I can register if I come from outside China? I received an error when trying to register for Baidu Cloud. Or maybe do you know another way to get access to Wenxin Word GPT?

CleanShot 2024-05-10 at 10  40 51@2x

**Comment by Puiching-Memory** [comment]
I don't know which one you can access, the first one is direct, the other pages are portal pages and can look messy.
[https://qianfan.cloud.baidu.com/](https://qianfan.cloud.baidu.com/)
[https://intl.cloud.baidu.com/](https://intl.cloud.baidu.com/)
[https://cloud.baidu.com/?from=console](https://cloud.baidu.com/?from=console)

**Comment by Puiching-Memory** [comment]
And I realized that wenxin is our Chinese pronunciation, and the official English name they use is ERNIE

**Comment by Puiching-Memory** [comment]
One of the reasons I use wenxin is because I can't sign up for an OpenAI account in my region, and in theory, langchan should be able to switch between different GPT easily.🫡

**Comment by 360macky** [comment]
> I don't know which one you can access, the first one is direct, the other pages are portal pages and can look messy.
> https://qianfan.cloud.baidu.com/
> https://intl.cloud.baidu.com/
> https://cloud.baidu.com/?from=console

Thanks for the links, but I can't register yet. Maybe with https://login.bce.baidu.com/new-reg?lang=en&from=portal, but I still require a +86 phone number.

> One of the reasons I use wenxin is because I can't sign up for an OpenAI account in my region, and in theory, langchan should be able to switch between different GPT easily.🫡

Understood!, Good idea. I think I'm going to add another provider to use OpenAI GPT models in that case...

**Review by 360macky — APPROVED** [review]

**Pull request merged**
